name: Publish module and generate docs
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest, windows-2019, macos-latest, macos-11]
    steps:
    - uses: actions/checkout@main
    - name: Invoke Pester
      shell: pwsh
      run: Invoke-Pester
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@main
      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true
      - name: Publish module and generate docs
        shell: pwsh
        run: ./build/publishmodule.ps1 -CompanyName "${{ vars.COMPANYNAME }}" -ModuleName "${{ vars.MODULENAME }}" -Tag "${{ steps.get-latest-tag.outputs.tag }}" -PSGalleryKey "${{ secrets.PSGALLERYKEY }}" -GitHubBaseURI "${{ vars.GITHUBBASEURI }}" -TechspaceBaseURI "${{ vars.TECHSPACEBASEURI }}" -ModuleDescription "${{ vars.PSMODULEDESCRIPTION }}" -ModulePSVersion "${{ vars.PSMODULEPOWERSHELLVERSION }}" -ModuleAuthor "${{ vars.MODULEAUTHOR }}" -Copyright "${{ vars.COPYRIGHT }}"
  commitDocs:
    name: Commit generated docs
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
  mergeToMain:
    runs-on: ubuntu-latest
    needs: commitDocs
    steps:
      - uses: actions/checkout@master
      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true
      - name: Merge develop -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: main
          message: Release of ${{ steps.get-latest-tag.outputs.tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}