name: Publish module

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Checkout
        run: echo "Check out"
      - name: Get Previous tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: previoustag
      - name: Tag name
        run: echo "Tag name = ${{ steps.previoustag.outputs.patch }}"
