name: Release pipeline
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest, windows-2019, macos-latest, macos-11]
    steps:
    - uses: actions/checkout@main
    - name: Invoke Pester
      shell: pwsh
      run: Invoke-Pester
  publish:
    name: Publish module
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@main
      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true
      - name: publishmodule.ps1
        shell: pwsh
        run: ./build/publishmodule.ps1 -CompanyName "${{ vars.COMPANYNAME }}" -ModuleName "${{ vars.MODULENAME }}" -Tag "${{ steps.get-latest-tag.outputs.tag }}" -PSGalleryKey "${{ secrets.PSGALLERYKEY }}" -GitHubBaseURI "${{ vars.GITHUBBASEURI }}" -TechspaceBaseURI "${{ vars.TECHSPACEBASEURI }}" -ModuleDescription "${{ vars.PSMODULEDESCRIPTION }}" -ModulePSVersion "${{ vars.PSMODULEPOWERSHELLVERSION }}" -ModuleAuthor "${{ vars.MODULEAUTHOR }}" -Copyright "${{ vars.COPYRIGHT }}"
  postPublish:
    name: Create post publish task
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@main
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/post-publish-tasks-issue.md