name: Run Pester tests

on:
  pull_request:
    paths:
    - 'tests/**'
  workflow_dispatch:

jobs:
  test:
    name: "On"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Invoke Pester
      shell: pwsh
      run: Invoke-Pester
